### ISSUE TITLE
todo : update agent image and branch and redeploy ssm

### ISSUE THREAD

**Issue by jmikedupont2** [meta-introspector/cloud-deployment-eliza#33]
wip

```
schemaVersion: '0.3'
description: Update Branch
assumeRole: '{{AutomationAssumeRole}}'
parameters:
  AutomationAssumeRole:
    default: ''
    description: (Optional) Rolename.
    type: String
  InstanceId:
    description: ID of the Instance.
    type: String
  BranchName:
    default: feature/voice2
    description: branch to deploy
    type: String
  GitRepo:
    default: https://github.com/meta-introspector/cloud-deployment-eliza
    description: what git repo to pull
    type: String
  AgentImage:
    type: String
    description: image to deploy
    default: h4ckermike/elizaos-eliza:signoz
mainSteps:
  - name: agentUpdate
    action: aws:runCommand
    maxAttempts: 3
    timeoutSeconds: 3600
    isEnd: true
    inputs:
      Parameters:
        commands:
          - '#!/bin/bash'
          - '# FIXME set the variables in the env'
          - '# optionally set in ssm'
          - sudo docker restart agent-docker.service
          - sudo docker logs agent-docker.service
          - ''
      InstanceIds:
        - '{{InstanceId}}'
      DocumentName: AWS-RunShellScript
    outputs:
      - Type: String
        Name: payload
        Selector: $.Payload
```
